### PR TITLE
Change splash screen to follow device theme

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by shilangyu** [comment]
Actually, while we're at it, it would be reasonable to set the lemmur logo as the splash screen (with a background following the device theme). I'll look into it.

**Review by shilangyu — APPROVED** [review]
Thank you for your contribution!

**Comment by mimi89999** [comment]
> Actually, while we're at it, it would be reasonable to set the lemmur logo as the splash screen (with a background following the device theme). I'll look into it.

On my device the splash screen is displayed only for a brief moment. I fear that the logo might just 'flash' for some users.

**Comment by shilangyu** [comment]
> On my device the splash screen is displayed only for a brief moment. I fear that the logo might just 'flash' for some users.

I implemented it and will post a PR once yours is merged, if you have time please check if this flashing is indeed a problem. I'll tag you in that PR (other apps seem to get away with this).

**Review by krawieck — APPROVED** [review]

**Pull request merged**
